package server

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.json
var openAPIDocument []byte

type toolDefinition struct {
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Method         string         `json:"method"`
	Path           string         `json:"path"`
	RequiredScopes []string       `json:"required_scopes"`
	SafetyLevel    string         `json:"safety_level"`
	InputSchema    map[string]any `json:"input_schema"`
}

func registerDocumentationRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /openapi.json", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/vnd.oai.openapi+json;version=3.1")
		w.Header().Set("Cache-Control", "public, max-age=60")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(openAPIDocument)
	})
	mux.HandleFunc("GET /api/v2/tools", func(w http.ResponseWriter, r *http.Request) {
		if _, ok := requireScope(w, r, "config:read"); !ok {
			return
		}
		tools := toolDefinitions()
		writeJSON(w, http.StatusOK, map[string]any{
			"ok": true, "status": "ready", "api_version": "v2",
			"count": len(tools), "tools": tools,
			"blockers": []any{}, "next_actions": []any{},
		})
	})
}

func toolDefinitions() []toolDefinition {
	object := func(properties map[string]any, required ...string) map[string]any {
		result := map[string]any{
			"type": "object", "properties": properties, "additionalProperties": false,
		}
		if len(required) > 0 {
			result["required"] = required
		}
		return result
	}
	stringProperty := func(description string) map[string]any {
		return map[string]any{"type": "string", "description": description}
	}
	jobID := object(map[string]any{"job_id": stringProperty("UUID of the durable job.")}, "job_id")
	return []toolDefinition{
		{Name: "get_operations_overview", Description: "Read local filesystem/database capacity, queues, open incidents, recent failures, backup state, and dropped-log count. Performs no external calls.", Method: "GET", Path: "/api/v2/operations/overview", RequiredScopes: []string{"operations:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "query_operational_logs", Description: "Query lightweight recursively redacted operational-log summaries by indexed time, level, component, keyword, HTTP status, error, request, trace, job, or attempt correlation. Large request/response attributes are intentionally omitted; fetch the selected log context by ID when needed.", Method: "GET", Path: "/api/v2/operational-logs", RequiredScopes: []string{"logs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"level": stringProperty("Comma-separated debug, info, warn, or error levels."), "component": stringProperty("Exact component."), "q": stringProperty("Indexed summary keyword."), "error_code": stringProperty("Exact error code."), "status_code": map[string]any{"type": "integer", "minimum": 100, "maximum": 599}, "request_id": stringProperty("Request correlation ID."), "trace_id": stringProperty("Trace UUID."), "job_id": stringProperty("Job UUID."), "attempt_id": stringProperty("Attempt UUID."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 500}, "cursor": stringProperty("Opaque stable (occurred_at,id) cursor; no exact total is computed.")})},
		{Name: "list_incidents", Description: "List actionable aggregated incidents without conflating them with audit events or planned manual gates.", Method: "GET", Path: "/api/v2/incidents", RequiredScopes: []string{"operations:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"status": map[string]any{"type": "string", "enum": []string{"open", "acknowledged", "resolved"}}, "severity": map[string]any{"type": "string", "enum": []string{"info", "warning", "critical"}}, "kind": stringProperty("Exact incident kind."), "job_id": stringProperty("Job UUID."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}, "cursor": stringProperty("Opaque stable cursor.")})},
		{Name: "get_incident", Description: "Read one incident, its occurrence count, job/trace links, and latest redacted evidence.", Method: "GET", Path: "/api/v2/incidents/{incident_id}", RequiredScopes: []string{"operations:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"incident_id": stringProperty("Incident UUID.")}, "incident_id")},
		{Name: "create_diagnostic", Description: "Create an immutable evidence-bound diagnosis for exactly one full job UUID, incident UUID, or operational log ID using an enabled configured provider. Correlation prefixes are not diagnostic targets. The model receives no tools and cannot change state.", Method: "POST", Path: "/api/v2/diagnostics", RequiredScopes: []string{"diagnostics:run"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"provider_id": stringProperty("Configured provider UUID."), "job_id": stringProperty("Full job UUID; mutually exclusive with other targets."), "incident_id": stringProperty("Full incident UUID; mutually exclusive with other targets."), "log_id": map[string]any{"type": "integer", "minimum": 1}}, "provider_id")},
		{Name: "get_diagnostic", Description: "Read a validated immutable diagnosis and bounded follow-up results with exact evidence references.", Method: "GET", Path: "/api/v2/diagnostics/{diagnostic_id}", RequiredScopes: []string{"diagnostics:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"diagnostic_id": stringProperty("Diagnostic UUID.")}, "diagnostic_id")},
		{Name: "list_jobs", Description: "List recent durable jobs with optional status filtering and an opaque stable cursor.", Method: "GET", Path: "/api/v2/jobs", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"status": map[string]any{"type": "string", "enum": []string{"draft", "queued", "running", "paused", "blocked", "failed", "complete", "cancelled"}}, "kind": map[string]any{"type": "string", "enum": []string{"retorrent", "daily_candidates"}}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "cursor": stringProperty("Opaque cursor returned by the previous page.")})},
		{Name: "list_daily_candidates", Description: "List the persisted ranked daily candidates with metadata, promotion state, duplicate evidence, reasons, risks, blockers, and a safe retorrent-job action.", Method: "GET", Path: "/api/v2/candidates/daily", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"source": stringProperty("Uppercase source tracker code."), "target": stringProperty("Uppercase target tracker code."), "date": map[string]any{"type": "string", "format": "date"}, "status": map[string]any{"type": "string", "enum": []string{"candidate", "blocked", "submitted", "expired"}}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "create_daily_candidate_job", Description: "Create a durable audited source scan, rule snapshot, metadata/duplicate evaluation, ranking, and daily summary job.", Method: "POST", Path: "/api/v2/candidates/daily", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."), "source": stringProperty("Uppercase source tracker code."), "target": stringProperty("Uppercase target tracker code."), "target_count": map[string]any{"type": "integer", "minimum": 1, "maximum": 25, "default": 10}, "scan_limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "page": map[string]any{"type": "integer", "minimum": 1}, "date": map[string]any{"type": "string", "format": "date"}, "execution_mode": map[string]any{"type": "string", "enum": []string{"auto", "step"}}}, "idempotency_key", "source", "target")},
		{Name: "submit_daily_candidate", Description: "Create an unconfirmed retorrent job from a selected ready candidate. Rule acceptance is never inferred and confirm_upload is forced false.", Method: "POST", Path: "/api/v2/candidates/{candidate_id}/retorrent-job", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"candidate_id": stringProperty("Selected candidate UUID."), "idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."), "execution_mode": map[string]any{"type": "string", "enum": []string{"auto", "step"}}, "stop_after_step": stringProperty("Optional workflow step boundary."), "downloader": map[string]any{"$ref": "#/components/schemas/RetorrentDownloader"}, "target_downloader": map[string]any{"$ref": "#/components/schemas/RetorrentDownloader"}, "screenshots": map[string]any{"$ref": "#/components/schemas/RetorrentScreenshots"}, "image_host": map[string]any{"$ref": "#/components/schemas/RetorrentImageHost"}}, "candidate_id", "idempotency_key")},
		{Name: "list_daily_candidate_schedules", Description: "List durable daily candidate schedules and their next/last run timestamps.", Method: "GET", Path: "/api/v2/schedules/daily-candidates", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "create_daily_candidate_schedule", Description: "Create a durable daily candidate schedule. Scheduling only creates recommendation jobs and never submits a candidate or uploads a torrent.", Method: "POST", Path: "/api/v2/schedules/daily-candidates", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"name": stringProperty("Unique schedule name."), "cron_expression": stringProperty("Daily cron subset: minute hour * * *."), "timezone": stringProperty("IANA timezone, normally Asia/Shanghai."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/DailyCandidateScheduleConfig"}}, "name", "cron_expression", "timezone", "config")},
		{Name: "update_daily_candidate_schedule", Description: "Enable, disable, or revise an existing daily candidate schedule without performing an immediate tracker action.", Method: "PATCH", Path: "/api/v2/schedules/daily-candidates/{schedule_id}", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"schedule_id": stringProperty("Schedule UUID."), "cron_expression": stringProperty("Daily cron subset: minute hour * * *."), "timezone": stringProperty("IANA timezone."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/DailyCandidateScheduleConfig"}}, "schedule_id")},
		{Name: "list_daily_candidate_schedule_runs", Description: "Audit each durable schedule trigger, job link, retry count, lease, and safe failure state.", Method: "GET", Path: "/api/v2/schedules/daily-candidates/{schedule_id}/runs", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"schedule_id": stringProperty("Schedule UUID."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}}, "schedule_id")},
		{Name: "list_notifications", Description: "List redacted in-app and external notification delivery state, retry count, payload fingerprint, and remote receipt hashes. A notification never implies candidate submission or torrent upload.", Method: "GET", Path: "/api/v2/notifications", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "reconcile_notification", Description: "Resolve an outcome_unknown notification with explicit evidence. verified_not_delivered permits one queued retry; verified_delivered never calls the endpoint again. Telegram/Discord require the exact numeric message id; WeCom/Feishu expose no message id.", Method: "POST", Path: "/api/v2/notifications/{notification_id}/reconcile", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"notification_id": stringProperty("Notification UUID."), "decision": map[string]any{"type": "string", "enum": []string{"verified_not_delivered", "verified_delivered"}}, "confirmed": map[string]any{"type": "boolean", "const": true}, "evidence_sha256": stringProperty("Lowercase SHA-256 of the operator's reconciliation evidence."), "observed_at": map[string]any{"type": "string", "format": "date-time"}, "message_id": stringProperty("Exact numeric Telegram/Discord message id; omit for enterprise WeChat and Feishu.")}, "notification_id", "decision", "confirmed", "evidence_sha256", "observed_at")},
		{Name: "list_audit_events", Description: "List recursively redacted global configuration and external-action audit events with stable pagination. Job workflow events use the separate hash-chained job event stream.", Method: "GET", Path: "/api/v2/audit-events", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"actor_type": stringProperty("Exact actor type filter."), "action": stringProperty("Exact audited action filter."), "resource_type": stringProperty("Exact resource type filter."), "resource_id": stringProperty("Exact resource identifier filter."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "cursor": stringProperty("Opaque stable cursor returned by the previous page.")})},
		{Name: "get_live_readiness", Description: "Evaluate local rules, credential field presence, downloader/image-host/screenshot/metadata-provider configuration, mounted downloads, and required binaries for U2/CHD to MTEAM. Performs no external calls, does not probe integrations, and always returns live_upload_authorized=false with confirm_upload=false.", Method: "GET", Path: "/api/v2/readiness/live", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"source": map[string]any{"type": "string", "enum": []string{"U2", "CHD"}}, "target": map[string]any{"type": "string", "const": "MTEAM"}, "downloader": stringProperty("Configured source downloader name."), "target_downloader": stringProperty("Optional target seeding downloader; defaults to downloader."), "image_host": stringProperty("Configured ImgBB, PTPimg, Imgbox, or Pixhost name."), "screenshot_profile": stringProperty("Enabled screenshot profile name."), "tmdb_provider": stringProperty("Configured TMDb provider name."), "ptgen_provider": stringProperty("Configured PTGen provider name.")}, "source", "target", "downloader", "image_host", "screenshot_profile", "tmdb_provider", "ptgen_provider")},
		{
			Name: "create_retorrent_job", Description: "Create an auditable retorrent workflow and return job_id immediately. Every source, rule, duplicate, material, upload, target-torrent, downloader injection, seeding, and summary boundary persists separate evidence; live upload requires explicit accept_rules and confirm_upload gates.",
			Method: "POST", Path: "/api/v2/jobs", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write",
			InputSchema: object(map[string]any{
				"idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."),
				"kind":            map[string]any{"type": "string", "const": "retorrent"},
				"execution_mode":  map[string]any{"type": "string", "enum": []string{"auto", "step"}},
				"stop_after_step": stringProperty("Optional workflow step boundary."),
				"input":           map[string]any{"$ref": "#/components/schemas/RetorrentInput"},
			}, "idempotency_key", "input"),
		},
		{Name: "get_job_status", Description: "Read status, blockers, next_actions, and resume_state.", Method: "GET", Path: "/api/v2/jobs/{job_id}", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "get_job_summary", Description: "Read status/blockers/resume data and, after completion, the stable retorrent summary with source/target hashes, rule fingerprints, duplicate gates, downloader seeding checks, and summary_file evidence.", Method: "GET", Path: "/api/v2/jobs/{job_id}/summary", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "get_job_attention", Description: "Read one operator-facing final issue and its available solutions. Unknown remote writes, rule acceptance, duplicates, seeding obligations, and upload confirmation are always non-executable guidance.", Method: "GET", Path: "/api/v2/jobs/{job_id}/attention", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "perform_job_action", Description: "Apply only a currently advertised executable retry or safe local repair using optimistic status, step, and blocker bindings. Safe repair requires confirmed=true and never changes rules, credentials, duplicate evidence, upload consent, or seeding requirements.", Method: "POST", Path: "/api/v2/jobs/{job_id}/actions", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "action_id": map[string]any{"type": "string", "enum": []string{"resume_job", "retry_step", "approve_safe_repair"}}, "expected_status": map[string]any{"type": "string"}, "expected_step": stringProperty("Exact current step."), "expected_blocker_code": stringProperty("Exact current primary blocker code."), "confirmed": map[string]any{"type": "boolean"}}, "job_id", "action_id", "expected_status")},
		{Name: "get_upload_preview", Description: "Load the integrity-verified generated target package, readable description, MediaInfo/BDInfo, screenshot references, packaging decisions, warnings, and immutable revision count before live upload.", Method: "GET", Path: "/api/v2/jobs/{job_id}/upload-preview", RequiredScopes: []string{"jobs:read", "audit:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "revise_upload_preview", Description: "Request a new immutable target-package revision from explicitly reviewed editable fields. The old artifact remains auditable, downstream steps are invalidated, and confirm_upload is reset to false.", Method: "POST", Path: "/api/v2/jobs/{job_id}/upload-preview/revisions", RequiredScopes: []string{"jobs:write", "audit:read"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "expected_package_sha256": stringProperty("Exact current package artifact SHA-256 for optimistic locking."), "fields": map[string]any{"$ref": "#/components/schemas/UploadPreviewRevisionFields"}}, "job_id", "expected_package_sha256", "fields")},
		{Name: "get_job_events", Description: "Read the append-only hash-chained job event audit stream.", Method: "GET", Path: "/api/v2/jobs/{job_id}/events", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "after": map[string]any{"type": "integer", "minimum": 0}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 500}}, "job_id")},
		{Name: "get_job_attempts", Description: "Read paginated per-step attempts with attempt numbers, stable error codes, timing, adapter identity, recursively redacted output/error details, and only a SHA-256 marker for each raw input snapshot.", Method: "GET", Path: "/api/v2/jobs/{job_id}/attempts", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 500}, "cursor": stringProperty("Opaque cursor returned by the previous page.")}, "job_id")},
		{Name: "download_artifact_evidence", Description: "Download a non-secret evidence artifact after the service re-verifies its immutable size and SHA-256. Raw torrent artifacts are always denied.", Method: "GET", Path: "/api/v2/jobs/{job_id}/artifacts/{artifact_id}/content", RequiredScopes: []string{"jobs:read", "audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "artifact_id": stringProperty("Artifact UUID from the same job.")}, "job_id", "artifact_id")},
		{Name: "resume_job", Description: "Resume a paused, blocked, or failed job with explicit recovery values. Unknown target/image uploads and partial or unknown downloader adds reject generic retries and require the exact current attempt plus an operator-confirmed reconciliation decision and evidence SHA-256. verified_uploaded and verified_remote_state perform read-only recovery and never repeat the external write.", Method: "POST", Path: "/api/v2/jobs/{job_id}/resume", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "resume_state": map[string]any{"type": "object", "additionalProperties": true, "properties": map[string]any{"reconciliation": map[string]any{"$ref": "#/components/schemas/JobReconciliation"}}}}, "job_id", "resume_state")},
		{Name: "replay_job", Description: "Create a fresh linked job from a blocked, failed, or cancelled job after resetting accept_rules, manual obligations, resume state, and confirm_upload. Running, paused, complete, reconciliation-required, unknown-outcome, active-recovery, and already externally written jobs are rejected.", Method: "POST", Path: "/api/v2/jobs/{job_id}/replay", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"job_id": stringProperty("Original job UUID."), "idempotency_key": stringProperty("Required Idempotency-Key HTTP header value for this replay intent."), "execution_mode": map[string]any{"type": "string", "enum": []string{"step", "auto"}, "default": "step"}, "stop_after_step": stringProperty("Optional fresh workflow boundary; the original boundary is not inherited.")}, "job_id", "idempotency_key")},
		{Name: "pause_job", Description: "Pause a runnable job at its durable current step. In-flight downloader_add, image_upload, target_upload, and target_inject external writes reject mid-step interruption; stop them at a step boundary.", Method: "POST", Path: "/api/v2/jobs/{job_id}/pause", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: jobID},
		{Name: "cancel_job", Description: "Cancel a job without deleting artifacts or downloaded data. In-flight downloader_add, image_upload, target_upload, and target_inject external writes reject mid-step interruption to prevent unknown outcomes.", Method: "POST", Path: "/api/v2/jobs/{job_id}/cancel", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: jobID},
		{Name: "list_sites", Description: "List configured site adapters and active rule fingerprints.", Method: "GET", Path: "/api/v2/sites", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_site", Description: "Create or update a site's display name, enabled state, aliases, and tags. Aliases are search metadata only; workflows still require the canonical site code, and configuration never grants runtime support.", Method: "PUT", Path: "/api/v2/sites/{site_code}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"site_code": stringProperty("Immutable canonical uppercase site code."), "name": stringProperty("Display name."), "adapter": map[string]any{"type": "string", "enum": []string{"config_only", "nexusphp", "mteam_api", "ttg"}}, "enabled": map[string]any{"type": "boolean"}, "aliases": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, "tags": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "site_code", "name", "adapter", "enabled", "aliases", "tags")},
		{Name: "get_active_site_rules", Description: "Read the active approved rule revision for a site.", Method: "GET", Path: "/api/v2/sites/{site_code}/rules/active", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code.")}, "site_code")},
		{Name: "get_site_access_policy", Description: "Read the fail-closed effective site access policy merged from an approved v2 rule and the operator's stricter interval, quota, and concurrency limits.", Method: "GET", Path: "/api/v2/sites/{site_code}/access-policy", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code.")}, "site_code")},
		{Name: "configure_site_access_policy", Description: "Configure operator site-access limits. This cannot override a forbidden or undetermined v2 rule, relax rule-derived minimum intervals/maximum quotas, or authorize a v1 rule.", Method: "PUT", Path: "/api/v2/sites/{site_code}/access-policy", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code."), "enabled": map[string]any{"type": "boolean"}, "general_min_interval_seconds": map[string]any{"type": "integer", "minimum": 1, "maximum": 86400}, "general_max_requests_per_hour": map[string]any{"type": "integer", "minimum": 1, "maximum": 3600}, "search_min_interval_seconds": map[string]any{"type": "integer", "minimum": 1, "maximum": 86400}, "search_max_requests_per_hour": map[string]any{"type": "integer", "minimum": 1, "maximum": 3600}, "max_concurrency": map[string]any{"type": "integer", "minimum": 1, "maximum": 4}}, "site_code", "enabled", "general_min_interval_seconds", "general_max_requests_per_hour", "search_min_interval_seconds", "search_max_requests_per_hour", "max_concurrency")},
		{Name: "get_site_rule_sources", Description: "Read the ordered exact HTTPS rule-page source set, per-source authentication mode, and redacted Cookie requirement/presence metadata without returning credentials or captured text.", Method: "GET", Path: "/api/v2/sites/{site_code}/rule-sources", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code.")}, "site_code")},
		{Name: "configure_site_rule_sources", Description: "Save 1..20 exact HTTPS rule-page URLs with per-source none/site_cookie authentication, stable evidence IDs/scopes, source completeness, and Cookie-host confirmation only when required. This performs no network request.", Method: "PUT", Path: "/api/v2/sites/{site_code}/rule-sources", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code."), "sources": map[string]any{"type": "array", "minItems": 1, "maxItems": 20, "items": map[string]any{"type": "object", "required": []string{"id", "url", "scope", "auth_mode"}, "properties": map[string]any{"auth_mode": map[string]any{"type": "string", "enum": []string{"none", "site_cookie"}}}}}, "scope_confirmed": map[string]any{"type": "boolean", "const": true}, "cookie_hosts_confirmed": map[string]any{"type": "boolean"}}, "site_code", "sources", "scope_confirmed", "cookie_hosts_confirmed")},
		{Name: "create_site_rule_collection", Description: "Explicitly queue one manual rule-page refresh using each source's saved authentication mode, normal access frequency gates, bounded evidence capture, and the configured rule-analysis provider. The durable run is bound to the exact non-secret provider endpoint/model/protocol/data-boundary/credential-version fingerprint and fails before fetch if that contract changes. Public sources receive no site credential; Cookie sources receive only the encrypted site Cookie. It imports only an immutable draft and never approves or activates it.", Method: "POST", Path: "/api/v2/sites/{site_code}/rule-collection-runs", RequiredScopes: []string{"config:manage"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code."), "source_set_fingerprint": stringProperty("Exact saved source-set SHA-256 fingerprint."), "provider_id": stringProperty("Configured rule_analysis provider UUID."), "idempotency_key": stringProperty("Required Idempotency-Key header."), "confirm": map[string]any{"type": "boolean", "const": true}}, "site_code", "source_set_fingerprint", "provider_id", "idempotency_key", "confirm")},
		{Name: "get_site_rule_collection", Description: "Read one durable collection run, per-page bounded evidence metadata, terminal error, and generated draft revision ID. This never starts or retries external work.", Method: "GET", Path: "/api/v2/site-rule-collection-runs/{run_id}", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"run_id": stringProperty("Rule collection run UUID.")}, "run_id")},
		{Name: "import_site_rules", Description: "Import an immutable Markdown rule revision as a draft. Incomplete drafts remain unapprovable and inactive.", Method: "POST", Path: "/api/v2/site-rules/import", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"markdown": stringProperty("Structured Markdown with YAML front matter and the captured original rule text, limited to 8 MiB of decoded UTF-8. Use source.complete=false until the relevant current rules have been fully reviewed.")}, "markdown")},
		{Name: "analyze_site_rule_revision", Description: "Explicitly send the server-bound immutable original text of one existing rule revision to a configured rule_analysis provider and return a validated editable draft. This synchronous tool endpoint performs external inference; Web uses the SSE heartbeat sibling /api/v2/site-rules/analyze/stream with an Idempotency-Key so proxy replays share one provider call, and polls /api/v2/site-rules/analyze/result with that same key if a browser-facing transport limit interrupts the stream. Large source text is split on evidence lines, extracted sequentially, and conservatively merged within one configured total timeout. Only normal protocol completion is accepted; truncated or incomplete outputs are never JSON-repaired. Successful SSE output and successful buffered responses are bounded to 8 MiB, failed buffered responses and individual aggregate SSE events to 1 MiB. Logs retain request/response metadata and hashes, never prompts or model-output text. It never imports, approves, activates, or authorizes the draft.", Method: "POST", Path: "/api/v2/site-rules/analyze", RequiredScopes: []string{"config:manage"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"provider_id": stringProperty("Configured provider UUID enabled for rule_analysis."), "source_revision_id": stringProperty("Existing immutable rule revision UUID; client-supplied source fields are ignored.")}, "provider_id", "source_revision_id")},
		{Name: "get_site_rule_review", Description: "Read the three human-reviewed hard gates (upload limits, download limits, and mandatory category-aware naming), multi-source conflicts, advisories, persisted decisions, blockers, and approval progress.", Method: "GET", Path: "/api/v2/site-rules/{revision_id}/review", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"revision_id": stringProperty("Rule revision UUID.")}, "revision_id")},
		{Name: "review_site_rule_section", Description: "Persist one confirmed or needs_changes decision for upload_limit, download_limit, or naming, bound to the exact revision fingerprint. Advisories do not require approval decisions.", Method: "PUT", Path: "/api/v2/site-rules/{revision_id}/review/{section}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Rule revision UUID."), "section": map[string]any{"type": "string", "enum": []string{"upload_limit", "download_limit", "naming"}}, "fingerprint": stringProperty("Exact current SHA-256 policy fingerprint."), "decision": map[string]any{"type": "string", "enum": []string{"confirmed", "needs_changes"}}, "comment": stringProperty("Required when decision is needs_changes.")}, "revision_id", "section", "fingerprint", "decision")},
		{Name: "correct_site_rule_hard_gate", Description: "Derive a new immutable draft after a human corrects an upload, download, or category-naming hard gate. Explicit data and an audit comment are required; review comments never become configuration, confirmations reset, and this never approves or activates the result.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/corrections/{section}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Source rule revision UUID."), "section": map[string]any{"type": "string", "enum": []string{"upload_limit", "download_limit", "naming"}}, "fingerprint": stringProperty("Exact source revision fingerprint."), "data": map[string]any{"type": "object", "description": "Section-specific declared/effective rate or complete naming data."}, "comment": stringProperty("Required human evidence and correction rationale, limited to 4000 bytes.")}, "revision_id", "section", "fingerprint", "data", "comment")},
		{Name: "approve_site_rules", Description: "Approve a complete draft only after upload, download, and category-aware naming hard gates are confirmed for its exact fingerprint and all multi-source conflicts are resolved.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/approve", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Rule revision UUID."), "fingerprint": stringProperty("Exact SHA-256 policy fingerprint."), "comment": stringProperty("Reviewer audit comment.")}, "revision_id", "fingerprint")},
		{Name: "activate_site_rules", Description: "Activate an approved rule revision for workflow enforcement.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/activate", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Approved rule revision UUID.")}, "revision_id")},
		{Name: "discard_site_rule_draft", Description: "Remove one pending draft from the maintenance workspace by marking it retired while retaining its immutable source, fingerprint, review evidence, and audit history.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/discard", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Draft rule revision UUID."), "fingerprint": stringProperty("Exact draft SHA-256 policy fingerprint."), "confirm": map[string]any{"type": "boolean", "const": true}}, "revision_id", "fingerprint", "confirm")},
		{Name: "list_adapter_capabilities", Description: "Read the fingerprinted capability, credential-field, safety-gate, constraint, and explicit unavailable-state contract for all adapters. This local catalog performs no external calls; never infer runtime support from an adapter or site name.", Method: "GET", Path: "/api/v2/adapters", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"kind": map[string]any{"type": "string", "enum": []string{"downloader", "image_host", "media_analyzer", "media_manager", "metadata_provider", "notification_channel", "screenshot_engine", "site", "torrent_maker"}}})},
		{Name: "list_downloader_adapters", Description: "Read the authoritative downloader runtime capability catalog before configuring or invoking an adapter.", Method: "GET", Path: "/api/v2/downloader-adapters", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "get_downloader_snapshot", Description: "Explicitly read one configured downloader's bounded torrent dashboard. Returns names, progress, speeds, ratios, categories, tags and aggregate counts without save paths, tracker URLs or credentials. The service coalesces concurrent reads and uses a short cache; this performs an external read and never changes torrent state.", Method: "GET", Path: "/api/v2/downloaders/{name}/snapshot", RequiredScopes: []string{"downloader:manage"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured downloader name."), "filter": map[string]any{"type": "string", "enum": []string{"all", "downloading", "seeding", "active", "paused", "checking", "error", "completed"}}, "query": stringProperty("Optional name, hash, category, or tag search, up to 200 characters."), "offset": map[string]any{"type": "integer", "minimum": 0}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}}, "name")},
		{Name: "configure_downloader", Description: "Add or update a remote downloader, its operator-reviewed unknown/home/seedbox network class, encrypted credentials, and path mappings. Seedbox status is never inferred. Adapters without a native runtime can only be saved disabled.", Method: "PUT", Path: "/api/v2/downloaders/{name}", RequiredScopes: []string{"downloader:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable downloader name."), "adapter": map[string]any{"type": "string", "enum": []string{"qbittorrent", "rtorrent", "deluge", "transmission"}}, "enabled": map[string]any{"type": "boolean"}, "network_class": map[string]any{"type": "string", "enum": []string{"unknown", "home", "seedbox"}}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}}, "path_mappings": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/PathMapping"}}}, "name", "adapter", "config")},
		{Name: "configure_image_host", Description: "Add or update an independently prioritized image host. ImgBB and PTPimg credentials are encrypted; Imgbox and Pixhost require no credentials. Saving does not test the remote service; Web exposes a separately confirmed one-pixel upload test.", Method: "PUT", Path: "/api/v2/image-hosts/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable image host name."), "adapter": map[string]any{"type": "string", "enum": []string{"imgbb", "ptpimg", "imgbox", "pixhost"}}, "enabled": map[string]any{"type": "boolean"}, "priority": map[string]any{"type": "integer"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "description": "api_key is required for ImgBB/PTPimg and omitted for Imgbox/Pixhost.", "additionalProperties": map[string]any{"type": "string"}}}, "name", "adapter", "config")},
		{Name: "list_notification_channels", Description: "List independently configured notification channels without returning webhook credentials.", Method: "GET", Path: "/api/v2/notification-channels", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_notification_channel", Description: "Configure Telegram Bot, enterprise WeChat, Feishu, or legacy Discord delivery with encrypted credentials and selected high-level job events. Saving does not send a message; Web exposes a separately confirmed durable test delivery. Delivery never changes workflow consent or safety gates.", Method: "PUT", Path: "/api/v2/notification-channels/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable channel name."), "adapter": map[string]any{"type": "string", "enum": []string{"telegram_bot", "wecom_bot", "feishu_bot", "discord_webhook"}}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/NotificationChannelConfig"}, "credentials": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string", "writeOnly": true}}}, "name", "adapter", "config")},
		{Name: "list_media_managers", Description: "List independent Sonarr and Radarr instances without returning API keys.", Method: "GET", Path: "/api/v2/media-managers", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_media_manager", Description: "Configure a Sonarr or Radarr v3 endpoint and encrypted api_key.", Method: "PUT", Path: "/api/v2/media-managers/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable media manager name."), "adapter": map[string]any{"type": "string", "enum": []string{"sonarr", "radarr"}}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "properties": map[string]any{"api_key": map[string]any{"type": "string", "writeOnly": true}}}}, "name", "adapter", "config")},
		{Name: "probe_media_manager", Description: "Explicitly perform an authenticated read-only system-status probe and persist version/configuration/response hash evidence.", Method: "POST", Path: "/api/v2/media-managers/{name}/probe", RequiredScopes: []string{"config:manage"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured media manager name.")}, "name")},
		{Name: "lookup_media_manager_metadata", Description: "Use one configured Sonarr or Radarr instance for a read-only metadata lookup. Audits query/response hashes and normalized IDs, never the local path or API key.", Method: "POST", Path: "/api/v2/media-managers/{name}/lookup", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured media manager name."), "tvdb_id": map[string]any{"type": "integer", "minimum": 1}, "tmdb_id": map[string]any{"type": "integer", "minimum": 1}, "path": stringProperty("Exact media path; persisted audit stores only its query hash."), "title": stringProperty("Release title required with Sonarr path parsing.")}, "name")},
		{Name: "list_metadata_providers", Description: "List independently configured TMDb and PTGen providers without returning API keys.", Method: "GET", Path: "/api/v2/metadata-providers", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_metadata_provider", Description: "Configure an explicit TMDb or PTGen endpoint with an encrypted api_key. Saving does not contact the provider; Web exposes a separate read-only production-contract test. PTGen never falls back to an implicit public endpoint.", Method: "PUT", Path: "/api/v2/metadata-providers/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable metadata provider name."), "adapter": map[string]any{"type": "string", "enum": []string{"tmdb", "ptgen"}}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "properties": map[string]any{"api_key": map[string]any{"type": "string", "writeOnly": true}}}}, "name", "adapter", "config")},
		{Name: "resolve_external_metadata", Description: "Explicitly query one configured TMDb or PTGen provider. Returns normalized IDs and bounded PTGen text while audits retain only configuration/query/response/description hashes.", Method: "POST", Path: "/api/v2/metadata-providers/{name}/resolve", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured provider name."), "imdb_id": stringProperty("IMDb tt identifier."), "tmdb_id": stringProperty("Numeric TMDb identifier."), "tmdb_type": map[string]any{"type": "string", "enum": []string{"movie", "tv"}}, "douban_id": stringProperty("Numeric Douban subject identifier.")}, "name")},
		{Name: "create_screenshot_profile", Description: "Create an immutable new screenshot configuration revision.", Method: "POST", Path: "/api/v2/screenshot-profiles", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Screenshot profile name."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/ScreenshotConfig"}}, "name", "config")},
		{Name: "preview_legacy_migration", Description: "Safely parse the fixed read-only legacy config mount without executing Python and return only redacted resource fields, warnings, and the exact source fingerprint.", Method: "GET", Path: "/api/v2/migrations/legacy/preview", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "execute_legacy_migration", Description: "Import the previously reviewed legacy source fingerprint into encrypted Go/PostgreSQL configuration. Requires explicit confirmation, performs no network probes, never deletes source files, and retains an encrypted source archive for 30 days.", Method: "POST", Path: "/api/v2/migrations/legacy", RequiredScopes: []string{"config:manage", "downloader:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"source_fingerprint": stringProperty("Exact master-keyed HMAC-SHA256 fingerprint returned by preview_legacy_migration."), "confirm_import": map[string]any{"type": "boolean", "const": true}}, "source_fingerprint", "confirm_import")},
		{Name: "list_legacy_migrations", Description: "List redacted legacy import reports and encrypted-archive retention state.", Method: "GET", Path: "/api/v2/migrations/legacy", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "get_legacy_migration", Description: "Read one redacted legacy import report, applied resource IDs, blockers, next actions, and archive expiry state. Archive plaintext and credentials are never returned.", Method: "GET", Path: "/api/v2/migrations/legacy/{import_id}", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"import_id": stringProperty("Legacy import UUID.")}, "import_id")},
	}
}
