package server

import (
	_ "embed"
	"net/http"
)

//go:embed openapi.json
var openAPIDocument []byte

type toolDefinition struct {
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Method         string         `json:"method"`
	Path           string         `json:"path"`
	RequiredScopes []string       `json:"required_scopes"`
	SafetyLevel    string         `json:"safety_level"`
	InputSchema    map[string]any `json:"input_schema"`
}

func registerDocumentationRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /openapi.json", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/vnd.oai.openapi+json;version=3.1")
		w.Header().Set("Cache-Control", "public, max-age=60")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(openAPIDocument)
	})
	mux.HandleFunc("GET /api/v2/tools", func(w http.ResponseWriter, r *http.Request) {
		if _, ok := requireScope(w, r, "config:read"); !ok {
			return
		}
		tools := toolDefinitions()
		writeJSON(w, http.StatusOK, map[string]any{
			"ok": true, "status": "ready", "api_version": "v2",
			"count": len(tools), "tools": tools,
			"blockers": []any{}, "next_actions": []any{},
		})
	})
}

func toolDefinitions() []toolDefinition {
	object := func(properties map[string]any, required ...string) map[string]any {
		result := map[string]any{
			"type": "object", "properties": properties, "additionalProperties": false,
		}
		if len(required) > 0 {
			result["required"] = required
		}
		return result
	}
	stringProperty := func(description string) map[string]any {
		return map[string]any{"type": "string", "description": description}
	}
	jobID := object(map[string]any{"job_id": stringProperty("UUID of the durable job.")}, "job_id")
	return []toolDefinition{
		{Name: "list_jobs", Description: "List recent durable jobs with optional status filtering and an opaque stable cursor.", Method: "GET", Path: "/api/v2/jobs", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"status": map[string]any{"type": "string", "enum": []string{"draft", "queued", "running", "paused", "blocked", "failed", "complete", "cancelled"}}, "kind": map[string]any{"type": "string", "enum": []string{"retorrent", "daily_candidates"}}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "cursor": stringProperty("Opaque cursor returned by the previous page.")})},
		{Name: "list_daily_candidates", Description: "List the persisted ranked daily candidates with metadata, promotion state, duplicate evidence, reasons, risks, blockers, and a safe retorrent-job action.", Method: "GET", Path: "/api/v2/candidates/daily", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"source": stringProperty("Uppercase source tracker code."), "target": stringProperty("Uppercase target tracker code."), "date": map[string]any{"type": "string", "format": "date"}, "status": map[string]any{"type": "string", "enum": []string{"candidate", "blocked", "submitted", "expired"}}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "create_daily_candidate_job", Description: "Create a durable audited source scan, rule snapshot, metadata/duplicate evaluation, ranking, and daily summary job.", Method: "POST", Path: "/api/v2/candidates/daily", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."), "source": stringProperty("Uppercase source tracker code."), "target": stringProperty("Uppercase target tracker code."), "target_count": map[string]any{"type": "integer", "minimum": 1, "maximum": 25, "default": 10}, "scan_limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "page": map[string]any{"type": "integer", "minimum": 1}, "date": map[string]any{"type": "string", "format": "date"}, "execution_mode": map[string]any{"type": "string", "enum": []string{"auto", "step"}}}, "idempotency_key", "source", "target")},
		{Name: "submit_daily_candidate", Description: "Create an unconfirmed retorrent job from a selected ready candidate. Rule acceptance is never inferred and confirm_upload is forced false.", Method: "POST", Path: "/api/v2/candidates/{candidate_id}/retorrent-job", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"candidate_id": stringProperty("Selected candidate UUID."), "idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."), "execution_mode": map[string]any{"type": "string", "enum": []string{"auto", "step"}}, "stop_after_step": stringProperty("Optional workflow step boundary."), "downloader": map[string]any{"$ref": "#/components/schemas/RetorrentDownloader"}, "target_downloader": map[string]any{"$ref": "#/components/schemas/RetorrentDownloader"}, "screenshots": map[string]any{"$ref": "#/components/schemas/RetorrentScreenshots"}, "image_host": map[string]any{"$ref": "#/components/schemas/RetorrentImageHost"}}, "candidate_id", "idempotency_key")},
		{Name: "list_daily_candidate_schedules", Description: "List durable daily candidate schedules and their next/last run timestamps.", Method: "GET", Path: "/api/v2/schedules/daily-candidates", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "create_daily_candidate_schedule", Description: "Create a durable daily candidate schedule. Scheduling only creates recommendation jobs and never submits a candidate or uploads a torrent.", Method: "POST", Path: "/api/v2/schedules/daily-candidates", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"name": stringProperty("Unique schedule name."), "cron_expression": stringProperty("Daily cron subset: minute hour * * *."), "timezone": stringProperty("IANA timezone, normally Asia/Shanghai."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/DailyCandidateScheduleConfig"}}, "name", "cron_expression", "timezone", "config")},
		{Name: "update_daily_candidate_schedule", Description: "Enable, disable, or revise an existing daily candidate schedule without performing an immediate tracker action.", Method: "PATCH", Path: "/api/v2/schedules/daily-candidates/{schedule_id}", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"schedule_id": stringProperty("Schedule UUID."), "cron_expression": stringProperty("Daily cron subset: minute hour * * *."), "timezone": stringProperty("IANA timezone."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/DailyCandidateScheduleConfig"}}, "schedule_id")},
		{Name: "list_daily_candidate_schedule_runs", Description: "Audit each durable schedule trigger, job link, retry count, lease, and safe failure state.", Method: "GET", Path: "/api/v2/schedules/daily-candidates/{schedule_id}/runs", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"schedule_id": stringProperty("Schedule UUID."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}}, "schedule_id")},
		{Name: "list_notifications", Description: "List redacted in-app and external notification delivery state, retry count, payload fingerprint, and remote receipt hashes. A notification never implies candidate submission or torrent upload.", Method: "GET", Path: "/api/v2/notifications", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "list_audit_events", Description: "List recursively redacted global configuration and external-action audit events with stable pagination. Job workflow events use the separate hash-chained job event stream.", Method: "GET", Path: "/api/v2/audit-events", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"actor_type": stringProperty("Exact actor type filter."), "action": stringProperty("Exact audited action filter."), "resource_type": stringProperty("Exact resource type filter."), "resource_id": stringProperty("Exact resource identifier filter."), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}, "cursor": stringProperty("Opaque stable cursor returned by the previous page.")})},
		{Name: "get_live_readiness", Description: "Evaluate local rules, credential field presence, downloader/image-host/screenshot configuration, mounted downloads, and required binaries for U2/CHD to MTEAM. Performs no external calls, does not probe integrations, and always returns live_upload_authorized=false with confirm_upload=false.", Method: "GET", Path: "/api/v2/readiness/live", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"source": map[string]any{"type": "string", "enum": []string{"U2", "CHD"}}, "target": map[string]any{"type": "string", "const": "MTEAM"}, "downloader": stringProperty("Configured source downloader name."), "target_downloader": stringProperty("Optional target seeding downloader; defaults to downloader."), "image_host": stringProperty("Configured imgbb or PTPimg name."), "screenshot_profile": stringProperty("Enabled screenshot profile name.")}, "source", "target", "downloader", "image_host", "screenshot_profile")},
		{
			Name: "create_retorrent_job", Description: "Create an auditable retorrent workflow and return job_id immediately. Every source, rule, duplicate, material, upload, target-torrent, downloader injection, seeding, and summary boundary persists separate evidence; live upload requires explicit accept_rules and confirm_upload gates.",
			Method: "POST", Path: "/api/v2/jobs", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write",
			InputSchema: object(map[string]any{
				"idempotency_key": stringProperty("Required Idempotency-Key HTTP header value."),
				"kind":            map[string]any{"type": "string", "const": "retorrent"},
				"execution_mode":  map[string]any{"type": "string", "enum": []string{"auto", "step"}},
				"stop_after_step": stringProperty("Optional workflow step boundary."),
				"input":           map[string]any{"$ref": "#/components/schemas/RetorrentInput"},
			}, "idempotency_key", "input"),
		},
		{Name: "get_job_status", Description: "Read status, blockers, next_actions, and resume_state.", Method: "GET", Path: "/api/v2/jobs/{job_id}", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "get_job_summary", Description: "Read status/blockers/resume data and, after completion, the stable retorrent summary with source/target hashes, rule fingerprints, duplicate gates, downloader seeding checks, and summary_file evidence.", Method: "GET", Path: "/api/v2/jobs/{job_id}/summary", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: jobID},
		{Name: "get_job_events", Description: "Read the append-only hash-chained job event audit stream.", Method: "GET", Path: "/api/v2/jobs/{job_id}/events", RequiredScopes: []string{"jobs:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "after": map[string]any{"type": "integer", "minimum": 0}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 500}}, "job_id")},
		{Name: "download_artifact_evidence", Description: "Download a non-secret evidence artifact after the service re-verifies its immutable size and SHA-256. Raw torrent artifacts are always denied.", Method: "GET", Path: "/api/v2/jobs/{job_id}/artifacts/{artifact_id}/content", RequiredScopes: []string{"jobs:read", "audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "artifact_id": stringProperty("Artifact UUID from the same job.")}, "job_id", "artifact_id")},
		{Name: "resume_job", Description: "Resume a paused, blocked, or failed job with explicit recovery values.", Method: "POST", Path: "/api/v2/jobs/{job_id}/resume", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: object(map[string]any{"job_id": stringProperty("Job UUID."), "resume_state": map[string]any{"type": "object", "additionalProperties": true}}, "job_id", "resume_state")},
		{Name: "pause_job", Description: "Pause a runnable job at its durable current step.", Method: "POST", Path: "/api/v2/jobs/{job_id}/pause", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: jobID},
		{Name: "cancel_job", Description: "Cancel a job. This does not delete artifacts or downloaded data.", Method: "POST", Path: "/api/v2/jobs/{job_id}/cancel", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "controlled_write", InputSchema: jobID},
		{Name: "list_sites", Description: "List configured site adapters and active rule fingerprints.", Method: "GET", Path: "/api/v2/sites", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "get_active_site_rules", Description: "Read the active approved rule revision for a site.", Method: "GET", Path: "/api/v2/sites/{site_code}/rules/active", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"site_code": stringProperty("Uppercase tracker code.")}, "site_code")},
		{Name: "import_site_rules", Description: "Import an immutable Markdown rule revision as a draft.", Method: "POST", Path: "/api/v2/site-rules/import", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"markdown": stringProperty("Complete Markdown document with YAML front matter and original rule text.")}, "markdown")},
		{Name: "approve_site_rules", Description: "Approve a complete draft using its exact fingerprint.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/approve", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Rule revision UUID."), "fingerprint": stringProperty("Exact SHA-256 policy fingerprint."), "comment": stringProperty("Reviewer audit comment.")}, "revision_id", "fingerprint")},
		{Name: "activate_site_rules", Description: "Activate an approved rule revision for workflow enforcement.", Method: "POST", Path: "/api/v2/site-rules/{revision_id}/activate", RequiredScopes: []string{"config:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"revision_id": stringProperty("Approved rule revision UUID.")}, "revision_id")},
		{Name: "list_downloader_adapters", Description: "Read the authoritative downloader runtime capability catalog before configuring or invoking an adapter.", Method: "GET", Path: "/api/v2/downloader-adapters", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_downloader", Description: "Add or update a remote downloader, encrypted credentials, and path mappings. Adapters without a native runtime can only be saved disabled.", Method: "PUT", Path: "/api/v2/downloaders/{name}", RequiredScopes: []string{"downloader:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable downloader name."), "adapter": map[string]any{"type": "string", "enum": []string{"qbittorrent", "rtorrent", "deluge", "transmission"}}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}}, "path_mappings": map[string]any{"type": "array", "items": map[string]any{"$ref": "#/components/schemas/PathMapping"}}}, "name", "adapter", "config")},
		{Name: "configure_image_host", Description: "Add or update an independently prioritized image host with encrypted credentials.", Method: "PUT", Path: "/api/v2/image-hosts/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable image host name."), "adapter": stringProperty("Image host adapter code."), "enabled": map[string]any{"type": "boolean"}, "priority": map[string]any{"type": "integer"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string"}}}, "name", "adapter", "config")},
		{Name: "list_notification_channels", Description: "List independently configured notification channels without returning webhook credentials.", Method: "GET", Path: "/api/v2/notification-channels", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_notification_channel", Description: "Configure an opt-in Discord incoming webhook channel. webhook_url is encrypted and never returned; delivery only occurs for schedules that explicitly name the channel.", Method: "PUT", Path: "/api/v2/notification-channels/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable channel name."), "adapter": map[string]any{"type": "string", "const": "discord_webhook"}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/NotificationChannelConfig"}, "credentials": map[string]any{"type": "object", "properties": map[string]any{"webhook_url": map[string]any{"type": "string", "writeOnly": true}}}}, "name", "adapter", "config")},
		{Name: "list_media_managers", Description: "List independent Sonarr and Radarr instances without returning API keys.", Method: "GET", Path: "/api/v2/media-managers", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "configure_media_manager", Description: "Configure a Sonarr or Radarr v3 endpoint and encrypted api_key.", Method: "PUT", Path: "/api/v2/media-managers/{name}", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Stable media manager name."), "adapter": map[string]any{"type": "string", "enum": []string{"sonarr", "radarr"}}, "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/EndpointConfig"}, "credentials": map[string]any{"type": "object", "properties": map[string]any{"api_key": map[string]any{"type": "string", "writeOnly": true}}}}, "name", "adapter", "config")},
		{Name: "probe_media_manager", Description: "Explicitly perform an authenticated read-only system-status probe and persist version/configuration/response hash evidence.", Method: "POST", Path: "/api/v2/media-managers/{name}/probe", RequiredScopes: []string{"config:manage"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured media manager name.")}, "name")},
		{Name: "lookup_media_manager_metadata", Description: "Use one configured Sonarr or Radarr instance for a read-only metadata lookup. Audits query/response hashes and normalized IDs, never the local path or API key.", Method: "POST", Path: "/api/v2/media-managers/{name}/lookup", RequiredScopes: []string{"jobs:write"}, SafetyLevel: "external_read", InputSchema: object(map[string]any{"name": stringProperty("Configured media manager name."), "tvdb_id": map[string]any{"type": "integer", "minimum": 1}, "tmdb_id": map[string]any{"type": "integer", "minimum": 1}, "path": stringProperty("Exact media path; persisted audit stores only its query hash."), "title": stringProperty("Release title required with Sonarr path parsing.")}, "name")},
		{Name: "create_screenshot_profile", Description: "Create an immutable new screenshot configuration revision.", Method: "POST", Path: "/api/v2/screenshot-profiles", RequiredScopes: []string{"config:manage"}, SafetyLevel: "configuration_write", InputSchema: object(map[string]any{"name": stringProperty("Screenshot profile name."), "enabled": map[string]any{"type": "boolean"}, "config": map[string]any{"$ref": "#/components/schemas/ScreenshotConfig"}}, "name", "config")},
		{Name: "preview_legacy_migration", Description: "Safely parse the fixed read-only legacy config mount without executing Python and return only redacted resource fields, warnings, and the exact source fingerprint.", Method: "GET", Path: "/api/v2/migrations/legacy/preview", RequiredScopes: []string{"config:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{})},
		{Name: "execute_legacy_migration", Description: "Import the previously reviewed legacy source fingerprint into encrypted Go/PostgreSQL configuration. Requires explicit confirmation, performs no network probes, never deletes source files, and retains an encrypted source archive for 30 days.", Method: "POST", Path: "/api/v2/migrations/legacy", RequiredScopes: []string{"config:manage", "downloader:manage"}, SafetyLevel: "privileged_write", InputSchema: object(map[string]any{"source_fingerprint": stringProperty("Exact master-keyed HMAC-SHA256 fingerprint returned by preview_legacy_migration."), "confirm_import": map[string]any{"type": "boolean", "const": true}}, "source_fingerprint", "confirm_import")},
		{Name: "list_legacy_migrations", Description: "List redacted legacy import reports and encrypted-archive retention state.", Method: "GET", Path: "/api/v2/migrations/legacy", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100}})},
		{Name: "get_legacy_migration", Description: "Read one redacted legacy import report, applied resource IDs, blockers, next actions, and archive expiry state. Archive plaintext and credentials are never returned.", Method: "GET", Path: "/api/v2/migrations/legacy/{import_id}", RequiredScopes: []string{"audit:read"}, SafetyLevel: "read_only", InputSchema: object(map[string]any{"import_id": stringProperty("Legacy import UUID.")}, "import_id")},
	}
}
